# Generated by Django 2.0.3 on 2021-07-08 14:17

import capacity.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcapacity',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(capacity.models.max_value_current_year)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopcapacity',
            name='entry_check',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workshopcapacity',
            name='exit_check',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workshopcapacity',
            name='retail_ready',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
